[package]
name = "rnex-node-holder"
version = "0.1.0"
edition = "2024"

[dependencies]
rnex-rmc = { path = "../../rnex-rmc" }
rnex-reggie-protos = { path = "../../rnex-protocols/reggie-protos" }
rnex-server = { path = "../../rnex-server" }
tokio = { version = "1.52.3", features = ["sync"] }
[lints]
workspace = true
