default:
  image: quay.io/podman/stable
  before_script:
    - git submodule update --init
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"

stages:
  - build_and_test

splatoon:
  stage: build_and_test
  script: ./.ci-scripts/make-edition.sh splatoon

friends:
  stage: build_and_test
  script: ./.ci-scripts/make-edition.sh friends
