[workspace]
resolver = "3"
members = [
    "prudpv1",
    "prudpv0",
    "proxy",
    "proxy-common",
    "rnex-rmc",
    "rnex-rmc/macros",
    "rnex-util",
    "rnex-protocols/mm-protos",
    "rnex-protocols/ds-protos",
    "rnex-protocols/rk-protos",
    "rnex-protocols/base-protos",
    "rnex-protocols/auth-protos",
    "rnex-protocols/reggie-protos",
    "rnex-protocols/msg-protos",
    "rnex-protocols/fpd-protos",
    "rnex-prudp",
    "rnex-server",
    "rnex-server/backend-auth",
    "rnex-server/backend-secure",
    "rnex-server/backend-node-holder",
    "rnex-server-nex-modules/rnex-mm",
    "rnex-server-nex-modules/rnex-ds",
    "rnex-server-nex-modules/rnex-rk",
    "rnex-server-nex-modules/rnex-fpd",
    "rnex-server-nex-modules/rnex-node-holder",
    "rnex-server-nex-modules/rnex-base",
    "rnex-server-nex-modules/rnex-msg",
    "rnex-server-nex-modules/rnex-auth"
, "prudpv1-proxy"]


[workspace.lints.clippy]
print_stdout = { level = "deny", priority = 1}
pedantic = { level = "warn", priority = 0 }
all = { level = "warn", priority = -1 }
