[package]
name = "rnex-rk"
version = "0.1.0"
edition = "2024"

[features]
rmc_struct_header = []
guest_login = []
friends = ["guest_login", "database-support"]
big_pid = []
third-notif-param = []
v3-3-2 = []
v3-4-0 = ["v3-3-2", "third-notif-param", "rmc_struct_header"]
v3-4-7 = ["v3-3-2"]
v3-5-0 = ["v3-4-0"]
v3-8-13 = ["v3-5-0"]
v3-8-15 = ["v3-5-0"]
v3-10-22 = ["v3-8-15"]
v4-3-11 = ["v3-8-15"]
nx = ["big_pid"]
splatoon = ["v3-5-0"]
datastore = ["database-support", "v3-8-15"]
database-support = []

[dependencies]
cfg-if = "1.0.4"
rnex-rmc = { path = "../../rnex-rmc" }
rnex-util = { path = "../../rnex-util" }
rnex-rk-protos = { path = "../../rnex-protocols/rk-protos" }
rnex-server = { path = "../../rnex-server" }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
ureq = { version = "3.3.0", features = ["json"] }
tokio = { version = "1.52.3", features = ["rt"] }
serde_json = "1.0.150"

[lints]
workspace = true
