name: Build and Test

on:
  push:
    branches: ["**"]

env:
  DOCKER_TLS_CERTDIR: /certs
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-editions:
    runs-on: debian-trixie
    strategy:
      fail-fast: false
      matrix:
        include:
          - edition: sonic-transformed
          - edition: mario-tennis
          - edition: wii-sports-club
            db_secret: DATABASE_SMM
          - edition: puyopuyo
            db_secret: DATABASE_SMM
          - edition: minecraft-wiiu
          - edition: splatoon-testfire
          - edition: fast-racing-neo
          - edition: wii-u-chat
          - edition: splatoon
          - edition: friends
            db_secret: DATABASE_FRIENDS
          - edition: super-mario-maker
            db_secret: DATABASE_SMM
          - edition: terraria
    
    name: ${{ matrix.edition }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Cache Cargo registry and target
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: cargo-${{ matrix.edition }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.edition }}-

      - name: Login to registry
        run: docker login -u ${{ secrets.PACKAGE_USER }} -p ${{ secrets.PACKAGE_PWD }} git.spbr.net

      - name: Set environment variables & build
        env:
          CI_REGISTRY_IMAGE: git.spbr.net/spacebar/rust-nex
          SHORT_SHA: ${{ github.sha }}
          DATABASE_URL: ${{ matrix.db_secret != '' && secrets[matrix.db_secret] || '' }}
        run: |
          echo "SHORT_SHA=${SHORT_SHA::6}" >> $GITHUB_ENV
          export CI_COMMIT_SHORT_SHA="${SHORT_SHA::6}"
          ./.forgejo/workflows/build.sh ${{ matrix.edition }}