[package]
name = "rnex-rk-protos"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
ctor = "1.0.8"
rnex-rmc = { path = "../../rnex-rmc" }
tracing = "0.1.44"
rnex-base-protos = { path = "../base-protos" }

[features]
splatoon = ["v3-5-0"]
datastore = ["database-support", "v3-8-15"]
database-support = []
nx = []
third-notif-param = []
v3-3-2 = []
v3-4-7 = ["v3-3-2"]
v3-4-0 = ["v3-3-2", "third-notif-param"]
v3-5-0 = ["v3-4-0"]
v3-8-13 = ["v3-5-0"]
v3-8-15 = ["v3-5-0"]
v3-10-22 = ["v3-8-15"]
v4-3-11 = ["v3-8-15"]
friends = []
rmc_struct_header = []
big_pid = []

[lints]
workspace = true
