[package]
name = "rnex-auth-protos"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.4"
ctor = "1.0.8"
rnex-rmc = { path = "../../rnex-rmc" }
tokio = { version = "1.52.3", features = ["time", "sync"] }
tracing = "0.1.44"

[features]
friends = []
splatoon = ["v3-5-0"]
datastore = ["database-support", "v3-8-15"]
database-support = []
nx = []
third-notif-param = []
v3-3-2 = []
v3-4-0 = ["v3-3-2", "third-notif-param"]
v3-5-0 = ["v3-4-0"]
v3-8-13 = ["v3-5-0"]
v3-8-15 = ["v3-5-0"]
v3-10-22 = ["v3-8-15"]
v4-3-11 = ["v3-8-15"]
rmc_struct_header = []
big_pid = []

[lints]
workspace = true
