[package]
name = "proxy-common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
thiserror = "2.0.12"
rnex-prudp = { path = "../rnex-prudp" }
rnex-server = { path = "../rnex-server" }
rnex-util = { path = "../rnex-util" }
rnex-rmc = { path = "../rnex-rmc" }
tokio = { version =  "1.47.0", features = ["full"] }
hex = "0.4.3"
tracing = "0.1.44"
