[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version =  "1.47.0", features = ["full"] }
prudpv0 = { path = "../prudpv0", optional = true }
prudpv1 = { path = "../prudpv1", optional = true }
proxy-common = { path = "../proxy-common" }
cfg-if = "1.0.4"
rnex-core = { path = "../rnex-core", version = "0.1.1" }
log = "0.4.25"

[features]
prudpv0 = ["dep:prudpv0"]
prudpv1 = ["dep:prudpv1"]
friends = ["prudpv0", "prudpv0/friends"]
splatoon = ["prudpv1"]


[[bin]]
name = "proxy_insecure"
path = "src/insecure.rs"

[[bin]]
name = "proxy_secure"
path = "src/secure.rs"
