[package]
name = "prudpv0"
version = "0.1.0"
edition = "2024"

[dependencies]
rnex-core = { path = "../rnex-core", version = "0.1.1" }
tokio = { version =  "1.47.0", features = ["full"] }
bytemuck = { version =  "1.23.1",  features = ["derive"] }
typenum = "1.18.0"
rc4 = "0.1.0"
log = "0.4.25"
cfg-if = "1.0.4"
proxy-common = {path = "../proxy-common"}
hmac = "0.12.1"
md-5 = "^0.10.6"

[features]
friends = []
