[package]
name = "rnex-msg"
version = "0.1.0"
edition = "2024"

[features]
rmc_struct_header = []
guest_login = []
friends = ["guest_login", "database-support"]
big_pid = []
third-notif-param = []
v3-3-2 = []
v3-4-0 = ["v3-3-2", "third-notif-param", "rmc_struct_header"]
v3-4-7 = ["v3-3-2"]
v3-5-0 = ["v3-4-0"]
v3-8-13 = ["v3-5-0"]
v3-8-15 = ["v3-5-0"]
v3-10-22 = ["v3-8-15"]
v4-3-11 = ["v3-8-15"]
nx = ["big_pid"]
splatoon = ["v3-5-0"]
datastore = ["database-support", "v3-8-15"]
database-support = []

[dependencies]
rnex-rmc = { path = "../../rnex-rmc" }
rnex-msg-protos = { path = "../../rnex-protocols/msg-protos" }
rnex-server = { path = "../../rnex-server" }
tokio = { version = "1.52.3", features = ["sync"] }

[lints]
workspace = true
